# Generated by Django 5.0.14 on 2026-03-28 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(help_text='Upload MP3 audio file (max 25MB)', upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'MP3'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transcribed_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_style', models.CharField(choices=[('concise', 'Concise (2-3 sentences)'), ('detailed', 'Detailed (comprehensive)'), ('bullet_points', 'Bullet Points (5-7 points)'), ('key_takeaways', 'Key Takeaways (actionable insights)')], default='concise', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('api_provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='openai', max_length=20)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Total processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Recording',
                'verbose_name_plural': 'Audio Recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='transcriber_status_819356_idx'), models.Index(fields=['created_at'], name='transcriber_created_249534_idx'), models.Index(fields=['api_provider'], name='transcriber_api_pro_e2cae5_idx')],
            },
        ),
    ]
